CREATE VIEW QTD_TOTAIS_POR_PRODUTO AS
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO

SELECT * FROM QTD_TOTAIS_POR_PRODUTO
WHERE QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;