-- Consulta para apontar quais clientes compraram fora do limite estipulado por mês/ano

SELECT CPF,NOME,VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM NOTAS_FISCAIS;

SELECT
    NF.CPF,
    TC.NOME,
    CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS mes_ano_venda,
    SUM(INF.QUANTIDADE) AS qtd_total,
    TC.VOLUME_DE_COMPRA,
    SUM(INF.QUANTIDADE) - TC.VOLUME_DE_COMPRA AS Desvio_Volume_max_mensal,
    CASE
        WHEN (SUM(INF.QUANTIDADE) - TC.VOLUME_DE_COMPRA) <= 0 THEN 'Dentro do limite'
        ELSE 'LIMITE ULTRAPASSADO'
    END AS Status_de_limite,
    ROUND((1-VOLUME_DE_COMPRA/SUM(QUANTIDADE))*100,2) AS perct_desvio
FROM
    NOTAS_FISCAIS NF
JOIN
    ITENS_NOTAS_FISCAIS INF ON INF.NUMERO = NF.NUMERO
JOIN
    TABELA_DE_CLIENTES TC ON TC.CPF = NF.CPF
GROUP BY
    TC.NOME,
    NF.CPF,
    CONVERT(VARCHAR(7), NF.DATA_VENDA, 120),
    TC.VOLUME_DE_COMPRA
HAVING
    SUM(INF.QUANTIDADE) > TC.VOLUME_DE_COMPRA
ORDER BY
    mes_ano_venda;

--Venda dos sucos por sabor e por ano 
SELECT CODIGO_DO_PRODUTO, SABOR,TAMANHO FROM TABELA_DE_PRODUTOS;

SELECT NUMERO,CODIGO_DO_PRODUTO,QUANTIDADE FROM ITENS_NOTAS_FISCAIS;

SELECT NUMERO,DATA_VENDA FROM NOTAS_FISCAIS;

SELECT
    ANO_VENDA,
    SABOR,
    QTD_TOTAL,
    SUM(QTD_TOTAL) OVER(PARTITION BY ANO_VENDA) AS TOTAL_VENDAS_POR_ANO,
    ROUND((CAST(QTD_TOTAL AS DECIMAL(10, 2)) / SUM(QTD_TOTAL) OVER(PARTITION BY ANO_VENDA)) * 100,2) AS PERCT_TOTAL_ANO
FROM (
    SELECT
        YEAR(NF.DATA_VENDA) AS ANO_VENDA,
        TP.SABOR,
        SUM(INF.QUANTIDADE) AS QTD_TOTAL
    FROM
        NOTAS_FISCAIS NF
    JOIN
        ITENS_NOTAS_FISCAIS INF ON INF.NUMERO = NF.NUMERO
    JOIN
        TABELA_DE_PRODUTOS TP ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
    GROUP BY
        YEAR(NF.DATA_VENDA),
        TP.SABOR
) AS VendasAgrupadas
ORDER BY
    ANO_VENDA, QTD_TOTAL DESC;