SELECT * FROM TABELA_DE_CLIENTES;



SELECT SUBSTRING(NOME,1,CHARINDEX(' ',NOME,1)-1) +
' nasceu em ' + 
DATENAME (WEEKDAY,DATA_DE_NASCIMENTO) + ',' +
DATENAME (DAY,DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(MONTH, DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(YEAR, DATA_DE_NASCIMENTO) AS DATA_EXTENSO
FROM TABELA_DE_CLIENTES;

WITH CTE AS(
SELECT
YEAR(NF.DATA_VENDA) AS ANO_VENDA,
INF.QUANTIDADE,
INF.PRECO,
INF.QUANTIDADE * INF.PRECO AS VLR_TOTAL,
NF.IMPOSTO,
FLOOR(NF.IMPOSTO * INF.QUANTIDADE * INF.PRECO) AS VLR_PAGO_IMPOSTO
FROM NOTAS_FISCAIS NF
JOIN ITENS_NOTAS_FISCAIS INF
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
)
SELECT ANO_VENDA,SUM(VLR_PAGO_IMPOSTO)
FROM CTE
GROUP BY ANO_VENDA;

SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);

SELECT
TC.NOME,
YEAR(NF.DATA_VENDA) AS ANO_VENDA,
CONCAT(
	'O cliente ',
	TC.NOME,
	' comprou R$ ',
	TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO),10,2))
	)AS VLR_TOTAL
FROM TABELA_DE_CLIENTES TC
JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
JOIN ITENS_NOTAS_FISCAIS INF
ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TC.NOME,YEAR(NF.DATA_VENDA);
