SELECT DISTINCT
TC.CPF AS CPF_TABELA_CLIENTES,
NOME,
NF.CPF AS CPF_NOTA_FISCAL
FROM TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;

--Selecionando os clientes que não tem vendedores em seus bairos e vendedores que estão alocados
--em bairros que não possuem vendedores:
SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
FULL JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;

SELECT DISTINCT SABOR
FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO IN 
(
	SELECT INF.CODIGO_DO_PRODUTO
	FROM ITENS_NOTAS_FISCAIS INF
	GROUP BY INF.CODIGO_DO_PRODUTO
	HAVING SUM(INF.QUANTIDADE) > 394000 
	)
