SELECT * FROM TABELA_DE_PRODUTOS
SELECT * FROM NOTAS_FISCAIS
SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT TP.NOME_DO_PRODUTO,COUNT(NF.NUMERO) as [numero de vendas]
FROM NOTAS_FISCAIS NF
JOIN ITENS_NOTAS_FISCAIS INF
	ON NF.NUMERO = INF.NUMERO
JOIN TABELA_DE_PRODUTOS TP
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
WHERE TP.NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'
GROUP BY TP.NOME_DO_PRODUTO
ORDER BY [numero de vendas] DESC;

SELECT TOP 5 NOME_DO_PRODUTO, QUANTIDADE
FROM ITENS_NOTAS_FISCAIS INF
JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'
ORDER BY QUANTIDADE DESC;

SELECT NOME_DO_PRODUTO, COUNT(QUANTIDADE)
FROM ITENS_NOTAS_FISCAIS INF
JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'
AND QUANTIDADE = 99
GROUP BY NOME_DO_PRODUTO

SELECT NOME_DO_PRODUTO, SUM(QUANTIDADE) AS total_vendido
FROM ITENS_NOTAS_FISCAIS INF
JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY NOME_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY total_vendido DESC;

SELECT
NOME,
LIMITE_DE_CREDITO,
CASE
	WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
	WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	ELSE 'CLIENTE PEQUENO' END AS CLASS_CLIENTE
FROM TABELA_DE_CLIENTES
ORDER BY LIMITE_DE_CREDITO DESC;